name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *"   # runs every 12 hours
  workflow_dispatch:        # allows manual run
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Generate snake animation
        uses: Platane/snk@v3.4.1
        with:
          github_user_name: uzuw
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark

      - name: Push generated files
        uses: EndBug/add-and-commit@v9
        with:
          message: "Generate snake animation"
          add: "dist/*"
